// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	result "github.com/dairlair/sentimentd/pkg/domain/service/training/result"
	mock "github.com/stretchr/testify/mock"
)

// ResultsRepositoryInterface is an autogenerated mock type for the ResultsRepositoryInterface type
type ResultsRepositoryInterface struct {
	mock.Mock
}

// SaveResult provides a mock function with given fields: brainID, res
func (_m *ResultsRepositoryInterface) SaveResult(brainID int64, res result.TrainingResult) error {
	ret := _m.Called(brainID, res)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, result.TrainingResult) error); ok {
		r0 = rf(brainID, res)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
