// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TokenServiceInterface is an autogenerated mock type for the TokenServiceInterface type
type TokenServiceInterface struct {
	mock.Mock
}

// FindOrCreate provides a mock function with given fields: brainID, text
func (_m *TokenServiceInterface) FindOrCreate(brainID int64, text string) int64 {
	ret := _m.Called(brainID, text)

	var r0 int64
	if rf, ok := ret.Get(0).(func(int64, string) int64); ok {
		r0 = rf(brainID, text)
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}
