// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	entity "github.com/dairlair/sentimentd/pkg/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// TokenServiceInterface is an autogenerated mock type for the TokenServiceInterface type
type TokenServiceInterface struct {
	mock.Mock
}

// FindOrCreate provides a mock function with given fields: brainID, text
func (_m *TokenServiceInterface) FindOrCreate(brainID int64, text string) (entity.TokenInterface, error) {
	ret := _m.Called(brainID, text)

	var r0 entity.TokenInterface
	if rf, ok := ret.Get(0).(func(int64, string) entity.TokenInterface); ok {
		r0 = rf(brainID, text)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(entity.TokenInterface)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64, string) error); ok {
		r1 = rf(brainID, text)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
