// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TokenizerInterface is an autogenerated mock type for the TokenizerInterface type
type TokenizerInterface struct {
	mock.Mock
}

// Tokenize provides a mock function with given fields: sentence
func (_m *TokenizerInterface) Tokenize(sentence string) []string {
	ret := _m.Called(sentence)

	var r0 []string
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(sentence)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}
