# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sentiment Analysis Daemon (sentimentd)
# email: dairlair@example.com
description: >
  High-performance sentiment analysis service
baseurl: "/sentimentd/"
url: "https://dairlair.github.io" # the base hostname & protocol for your site
twitter_username: dairlair
github_username:  dairlair

# Build settings
markdown: kramdown

google_analytics: "UA-156352365-1"
